name: Hello World Python Script

on:
  push:
    branches:
      - main  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have any dependencies

    - name: Output list of files in the working directory
      run: ls

  linting:
    runs-on: ubuntu-latest
    needs: build 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have any dependencies

    - name: Checks if the code is of good quality
      run: isort --check-only --profile black --line-length 70 -w 70 src/
      run: black --exclude .+\.ipynb --check --line-length 70 --line-length 70 src/
      run: flake8 --show-source --statistics --max-line-length 70 --max-line-length=70 src/ tests/

  test:
    runs-on: ubuntu-latest
    needs: build 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Run Tests
      run: python src/hello.py